baseURL = 'https://zullq86w.github.io'
languageCode = 'zh-cn'
title = 'çˆ±åƒçŒ«çš„é±¼'
theme = "stack"


DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  compact = false
  emoji = "ğŸ¥"
  subtitle = "å¤©é“é…¬å‹¤"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  headingAnchor = false
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "giscus"

    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.beaudar]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta = [ "nick", "mail" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.giscus]
      repo = "zuLLq86w/zullq86w.github.io"
      repo_id = "R_kgDONizpTA"
      category = "Announcements"
      category_id = "DIC_kwDONizpTM4Cn4vL"
      mapping = "pathname"
      strict = 0
      reactions_enabled = 1
      emit_metadata = 0
      input_position = "bottom"
      theme = "preferred_color_scheme"
      lang = "zh-CN"
      loading = "lazy"
      crossorigin = "anonymous"

    [params.comments.gitalk]

    [params.comments.cusdis]

  [params.widgets]
    homepage = [
      { type = "search", params = { title = "æœç´¢"}},
      { type = "archives", params = { limit = 10}},
      { type = "categories", params = {limit = 10}}
    ]
    page = [{type = "toc"}]


[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menus]
  [[menus.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/zuLLq86w"
    [menus.social.params]
      icon = "brand-github"

  [[menus.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com"
    [menus.social.params]
      icon = "brand-twitter"


